import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import HeaderSection from "./components/header/page";
import NavList from "./components/Nav/page";
import MarqueeSection from "./components/marque/page";

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Buzar Dor | বাজার দর",
  description: "Generated by create next app",
  icons: {
    icon: "/image/logo-icon.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-color-white">
        <Suspense fallback={<div className="p-4">Loading...</div>}>
          <HeaderSection />
          <NavList />
          <MarqueeSection />
        </Suspense>
        <>{children}</>
        <ToastContainer />
      </body>
    </html>
  );
}
